import { ReduxProvider } from '../../redux/features/provider';
import '../(content)/globals.css'
import { cookies } from "next/headers";
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import SupabaseListener from '../../features/auth/supabseListener';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  console.log(cookies())
  const supabase = createServerComponentClient({cookies,})
  const {data :{session}} = await supabase.auth.getSession()
  return (
    <html lang="en">
      <body className='overflow-hidden bg-neutral-800'>
        <ReduxProvider>   
          <SupabaseListener accessToken={session?.access_token}/>
          {children}
        </ReduxProvider>
      </body>
    </html>
  )
}
