import './globals.css'
import React from 'react';
import HeaderLayout from '../../features/headerLayout';
import AsideLayout from '../../features/asideLayout';
import type { Metadata } from 'next'
import { ReduxProvider } from '../../redux/features/provider';
import SupabaseListener from '../../features/auth/supabseListener';
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs';
import { cookies } from 'next/headers';

export const metadata: Metadata = {
  title: 'todo app',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  console.log(cookies())
  const supabase = createServerComponentClient({ cookies })
  const { data: { session } } = await supabase.auth.getSession()

  return (
    <html lang="ja">
      <body className='overflow-hidden bg-neutral-800'>
        <ReduxProvider>
          <SupabaseListener accessToken={session?.access_token} />
          <HeaderLayout />
          <main className={`h-[calc(100vh-48px)] flex`}>
            <AsideLayout />
            <div className='flex-grow'>
              {children}
            </div>
          </main>
        </ReduxProvider>
      </body>
    </html>
  )
}
